/**
 *
 *  BusAssignments.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "BusAssignments.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::postgres;

const std::string BusAssignments::Cols::_id = "\"id\"";
const std::string BusAssignments::Cols::_bus_id = "\"bus_id\"";
const std::string BusAssignments::Cols::_route_id = "\"route_id\"";
const std::string BusAssignments::Cols::_driver_id = "\"driver_id\"";
const std::string BusAssignments::Cols::_conductor_id = "\"conductor_id\"";
const std::string BusAssignments::Cols::_status = "\"status\"";
const std::string BusAssignments::Cols::_assignment_date = "\"assignment_date\"";
const std::string BusAssignments::Cols::_created_at = "\"created_at\"";
const std::string BusAssignments::primaryKeyName = "id";
const bool BusAssignments::hasPrimaryKey = true;
const std::string BusAssignments::tableName = "\"bus_assignments\"";

const std::vector<typename BusAssignments::MetaData> BusAssignments::metaData_={
{"id","std::string","uuid",0,0,1,1},
{"bus_id","std::string","uuid",0,0,0,0},
{"route_id","std::string","uuid",0,0,0,0},
{"driver_id","std::string","uuid",0,0,0,0},
{"conductor_id","std::string","uuid",0,0,0,0},
{"status","std::string","character varying",50,0,0,0},
{"assignment_date","::trantor::Date","date",0,0,0,1},
{"created_at","::trantor::Date","timestamp without time zone",0,0,0,0}
};
const std::string &BusAssignments::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
BusAssignments::BusAssignments(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<std::string>(r["id"].as<std::string>());
        }
        if(!r["bus_id"].isNull())
        {
            busId_=std::make_shared<std::string>(r["bus_id"].as<std::string>());
        }
        if(!r["route_id"].isNull())
        {
            routeId_=std::make_shared<std::string>(r["route_id"].as<std::string>());
        }
        if(!r["driver_id"].isNull())
        {
            driverId_=std::make_shared<std::string>(r["driver_id"].as<std::string>());
        }
        if(!r["conductor_id"].isNull())
        {
            conductorId_=std::make_shared<std::string>(r["conductor_id"].as<std::string>());
        }
        if(!r["status"].isNull())
        {
            status_=std::make_shared<std::string>(r["status"].as<std::string>());
        }
        if(!r["assignment_date"].isNull())
        {
            auto daysStr = r["assignment_date"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            assignmentDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
        if(!r["created_at"].isNull())
        {
            auto timeStr = r["created_at"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 8 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            busId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            routeId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            driverId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            conductorId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            status_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            auto daysStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            assignmentDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
        index = offset + 7;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }

}

BusAssignments::BusAssignments(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 8)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            busId_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            routeId_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            driverId_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            conductorId_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            status_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            auto daysStr = pJson[pMasqueradingVector[6]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            assignmentDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[7]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

BusAssignments::BusAssignments(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<std::string>(pJson["id"].asString());
        }
    }
    if(pJson.isMember("bus_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["bus_id"].isNull())
        {
            busId_=std::make_shared<std::string>(pJson["bus_id"].asString());
        }
    }
    if(pJson.isMember("route_id"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["route_id"].isNull())
        {
            routeId_=std::make_shared<std::string>(pJson["route_id"].asString());
        }
    }
    if(pJson.isMember("driver_id"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["driver_id"].isNull())
        {
            driverId_=std::make_shared<std::string>(pJson["driver_id"].asString());
        }
    }
    if(pJson.isMember("conductor_id"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["conductor_id"].isNull())
        {
            conductorId_=std::make_shared<std::string>(pJson["conductor_id"].asString());
        }
    }
    if(pJson.isMember("status"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["status"].isNull())
        {
            status_=std::make_shared<std::string>(pJson["status"].asString());
        }
    }
    if(pJson.isMember("assignment_date"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["assignment_date"].isNull())
        {
            auto daysStr = pJson["assignment_date"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            assignmentDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    if(pJson.isMember("created_at"))
    {
        dirtyFlag_[7]=true;
        if(!pJson["created_at"].isNull())
        {
            auto timeStr = pJson["created_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void BusAssignments::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 8)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            busId_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            routeId_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            driverId_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            conductorId_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            status_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            auto daysStr = pJson[pMasqueradingVector[6]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            assignmentDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[7]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void BusAssignments::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<std::string>(pJson["id"].asString());
        }
    }
    if(pJson.isMember("bus_id"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["bus_id"].isNull())
        {
            busId_=std::make_shared<std::string>(pJson["bus_id"].asString());
        }
    }
    if(pJson.isMember("route_id"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["route_id"].isNull())
        {
            routeId_=std::make_shared<std::string>(pJson["route_id"].asString());
        }
    }
    if(pJson.isMember("driver_id"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["driver_id"].isNull())
        {
            driverId_=std::make_shared<std::string>(pJson["driver_id"].asString());
        }
    }
    if(pJson.isMember("conductor_id"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["conductor_id"].isNull())
        {
            conductorId_=std::make_shared<std::string>(pJson["conductor_id"].asString());
        }
    }
    if(pJson.isMember("status"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["status"].isNull())
        {
            status_=std::make_shared<std::string>(pJson["status"].asString());
        }
    }
    if(pJson.isMember("assignment_date"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["assignment_date"].isNull())
        {
            auto daysStr = pJson["assignment_date"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            strptime(daysStr.c_str(),"%Y-%m-%d",&stm);
            time_t t = mktime(&stm);
            assignmentDate_=std::make_shared<::trantor::Date>(t*1000000);
        }
    }
    if(pJson.isMember("created_at"))
    {
        dirtyFlag_[7] = true;
        if(!pJson["created_at"].isNull())
        {
            auto timeStr = pJson["created_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

const std::string &BusAssignments::getValueOfId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<std::string> &BusAssignments::getId() const noexcept
{
    return id_;
}
void BusAssignments::setId(const std::string &pId) noexcept
{
    id_ = std::make_shared<std::string>(pId);
    dirtyFlag_[0] = true;
}
void BusAssignments::setId(std::string &&pId) noexcept
{
    id_ = std::make_shared<std::string>(std::move(pId));
    dirtyFlag_[0] = true;
}
const typename BusAssignments::PrimaryKeyType & BusAssignments::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const std::string &BusAssignments::getValueOfBusId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(busId_)
        return *busId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &BusAssignments::getBusId() const noexcept
{
    return busId_;
}
void BusAssignments::setBusId(const std::string &pBusId) noexcept
{
    busId_ = std::make_shared<std::string>(pBusId);
    dirtyFlag_[1] = true;
}
void BusAssignments::setBusId(std::string &&pBusId) noexcept
{
    busId_ = std::make_shared<std::string>(std::move(pBusId));
    dirtyFlag_[1] = true;
}
void BusAssignments::setBusIdToNull() noexcept
{
    busId_.reset();
    dirtyFlag_[1] = true;
}

const std::string &BusAssignments::getValueOfRouteId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(routeId_)
        return *routeId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &BusAssignments::getRouteId() const noexcept
{
    return routeId_;
}
void BusAssignments::setRouteId(const std::string &pRouteId) noexcept
{
    routeId_ = std::make_shared<std::string>(pRouteId);
    dirtyFlag_[2] = true;
}
void BusAssignments::setRouteId(std::string &&pRouteId) noexcept
{
    routeId_ = std::make_shared<std::string>(std::move(pRouteId));
    dirtyFlag_[2] = true;
}
void BusAssignments::setRouteIdToNull() noexcept
{
    routeId_.reset();
    dirtyFlag_[2] = true;
}

const std::string &BusAssignments::getValueOfDriverId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(driverId_)
        return *driverId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &BusAssignments::getDriverId() const noexcept
{
    return driverId_;
}
void BusAssignments::setDriverId(const std::string &pDriverId) noexcept
{
    driverId_ = std::make_shared<std::string>(pDriverId);
    dirtyFlag_[3] = true;
}
void BusAssignments::setDriverId(std::string &&pDriverId) noexcept
{
    driverId_ = std::make_shared<std::string>(std::move(pDriverId));
    dirtyFlag_[3] = true;
}
void BusAssignments::setDriverIdToNull() noexcept
{
    driverId_.reset();
    dirtyFlag_[3] = true;
}

const std::string &BusAssignments::getValueOfConductorId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(conductorId_)
        return *conductorId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &BusAssignments::getConductorId() const noexcept
{
    return conductorId_;
}
void BusAssignments::setConductorId(const std::string &pConductorId) noexcept
{
    conductorId_ = std::make_shared<std::string>(pConductorId);
    dirtyFlag_[4] = true;
}
void BusAssignments::setConductorId(std::string &&pConductorId) noexcept
{
    conductorId_ = std::make_shared<std::string>(std::move(pConductorId));
    dirtyFlag_[4] = true;
}
void BusAssignments::setConductorIdToNull() noexcept
{
    conductorId_.reset();
    dirtyFlag_[4] = true;
}

const std::string &BusAssignments::getValueOfStatus() const noexcept
{
    static const std::string defaultValue = std::string();
    if(status_)
        return *status_;
    return defaultValue;
}
const std::shared_ptr<std::string> &BusAssignments::getStatus() const noexcept
{
    return status_;
}
void BusAssignments::setStatus(const std::string &pStatus) noexcept
{
    status_ = std::make_shared<std::string>(pStatus);
    dirtyFlag_[5] = true;
}
void BusAssignments::setStatus(std::string &&pStatus) noexcept
{
    status_ = std::make_shared<std::string>(std::move(pStatus));
    dirtyFlag_[5] = true;
}
void BusAssignments::setStatusToNull() noexcept
{
    status_.reset();
    dirtyFlag_[5] = true;
}

const ::trantor::Date &BusAssignments::getValueOfAssignmentDate() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(assignmentDate_)
        return *assignmentDate_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &BusAssignments::getAssignmentDate() const noexcept
{
    return assignmentDate_;
}
void BusAssignments::setAssignmentDate(const ::trantor::Date &pAssignmentDate) noexcept
{
    assignmentDate_ = std::make_shared<::trantor::Date>(pAssignmentDate.roundDay());
    dirtyFlag_[6] = true;
}

const ::trantor::Date &BusAssignments::getValueOfCreatedAt() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(createdAt_)
        return *createdAt_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &BusAssignments::getCreatedAt() const noexcept
{
    return createdAt_;
}
void BusAssignments::setCreatedAt(const ::trantor::Date &pCreatedAt) noexcept
{
    createdAt_ = std::make_shared<::trantor::Date>(pCreatedAt);
    dirtyFlag_[7] = true;
}
void BusAssignments::setCreatedAtToNull() noexcept
{
    createdAt_.reset();
    dirtyFlag_[7] = true;
}

void BusAssignments::updateId(const uint64_t id)
{
}

const std::vector<std::string> &BusAssignments::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "id",
        "bus_id",
        "route_id",
        "driver_id",
        "conductor_id",
        "status",
        "assignment_date",
        "created_at"
    };
    return inCols;
}

void BusAssignments::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getId())
        {
            binder << getValueOfId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getBusId())
        {
            binder << getValueOfBusId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getRouteId())
        {
            binder << getValueOfRouteId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getDriverId())
        {
            binder << getValueOfDriverId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getConductorId())
        {
            binder << getValueOfConductorId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getStatus())
        {
            binder << getValueOfStatus();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getAssignmentDate())
        {
            binder << getValueOfAssignmentDate();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getCreatedAt())
        {
            binder << getValueOfCreatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> BusAssignments::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    if(dirtyFlag_[7])
    {
        ret.push_back(getColumnName(7));
    }
    return ret;
}

void BusAssignments::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getId())
        {
            binder << getValueOfId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getBusId())
        {
            binder << getValueOfBusId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getRouteId())
        {
            binder << getValueOfRouteId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getDriverId())
        {
            binder << getValueOfDriverId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getConductorId())
        {
            binder << getValueOfConductorId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getStatus())
        {
            binder << getValueOfStatus();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getAssignmentDate())
        {
            binder << getValueOfAssignmentDate();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getCreatedAt())
        {
            binder << getValueOfCreatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value BusAssignments::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getBusId())
    {
        ret["bus_id"]=getValueOfBusId();
    }
    else
    {
        ret["bus_id"]=Json::Value();
    }
    if(getRouteId())
    {
        ret["route_id"]=getValueOfRouteId();
    }
    else
    {
        ret["route_id"]=Json::Value();
    }
    if(getDriverId())
    {
        ret["driver_id"]=getValueOfDriverId();
    }
    else
    {
        ret["driver_id"]=Json::Value();
    }
    if(getConductorId())
    {
        ret["conductor_id"]=getValueOfConductorId();
    }
    else
    {
        ret["conductor_id"]=Json::Value();
    }
    if(getStatus())
    {
        ret["status"]=getValueOfStatus();
    }
    else
    {
        ret["status"]=Json::Value();
    }
    if(getAssignmentDate())
    {
        ret["assignment_date"]=getAssignmentDate()->toDbStringLocal();
    }
    else
    {
        ret["assignment_date"]=Json::Value();
    }
    if(getCreatedAt())
    {
        ret["created_at"]=getCreatedAt()->toDbStringLocal();
    }
    else
    {
        ret["created_at"]=Json::Value();
    }
    return ret;
}

std::string BusAssignments::toString() const
{
    return toJson().toStyledString();
}

Json::Value BusAssignments::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 8)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getBusId())
            {
                ret[pMasqueradingVector[1]]=getValueOfBusId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getRouteId())
            {
                ret[pMasqueradingVector[2]]=getValueOfRouteId();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getDriverId())
            {
                ret[pMasqueradingVector[3]]=getValueOfDriverId();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getConductorId())
            {
                ret[pMasqueradingVector[4]]=getValueOfConductorId();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getStatus())
            {
                ret[pMasqueradingVector[5]]=getValueOfStatus();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getAssignmentDate())
            {
                ret[pMasqueradingVector[6]]=getAssignmentDate()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[7].empty())
        {
            if(getCreatedAt())
            {
                ret[pMasqueradingVector[7]]=getCreatedAt()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[7]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getBusId())
    {
        ret["bus_id"]=getValueOfBusId();
    }
    else
    {
        ret["bus_id"]=Json::Value();
    }
    if(getRouteId())
    {
        ret["route_id"]=getValueOfRouteId();
    }
    else
    {
        ret["route_id"]=Json::Value();
    }
    if(getDriverId())
    {
        ret["driver_id"]=getValueOfDriverId();
    }
    else
    {
        ret["driver_id"]=Json::Value();
    }
    if(getConductorId())
    {
        ret["conductor_id"]=getValueOfConductorId();
    }
    else
    {
        ret["conductor_id"]=Json::Value();
    }
    if(getStatus())
    {
        ret["status"]=getValueOfStatus();
    }
    else
    {
        ret["status"]=Json::Value();
    }
    if(getAssignmentDate())
    {
        ret["assignment_date"]=getAssignmentDate()->toDbStringLocal();
    }
    else
    {
        ret["assignment_date"]=Json::Value();
    }
    if(getCreatedAt())
    {
        ret["created_at"]=getCreatedAt()->toDbStringLocal();
    }
    else
    {
        ret["created_at"]=Json::Value();
    }
    return ret;
}

bool BusAssignments::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("bus_id"))
    {
        if(!validJsonOfField(1, "bus_id", pJson["bus_id"], err, true))
            return false;
    }
    if(pJson.isMember("route_id"))
    {
        if(!validJsonOfField(2, "route_id", pJson["route_id"], err, true))
            return false;
    }
    if(pJson.isMember("driver_id"))
    {
        if(!validJsonOfField(3, "driver_id", pJson["driver_id"], err, true))
            return false;
    }
    if(pJson.isMember("conductor_id"))
    {
        if(!validJsonOfField(4, "conductor_id", pJson["conductor_id"], err, true))
            return false;
    }
    if(pJson.isMember("status"))
    {
        if(!validJsonOfField(5, "status", pJson["status"], err, true))
            return false;
    }
    if(pJson.isMember("assignment_date"))
    {
        if(!validJsonOfField(6, "assignment_date", pJson["assignment_date"], err, true))
            return false;
    }
    else
    {
        err="The assignment_date column cannot be null";
        return false;
    }
    if(pJson.isMember("created_at"))
    {
        if(!validJsonOfField(7, "created_at", pJson["created_at"], err, true))
            return false;
    }
    return true;
}
bool BusAssignments::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                        const std::vector<std::string> &pMasqueradingVector,
                                                        std::string &err)
{
    if(pMasqueradingVector.size() != 8)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[6] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[7].empty())
      {
          if(pJson.isMember(pMasqueradingVector[7]))
          {
              if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool BusAssignments::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("bus_id"))
    {
        if(!validJsonOfField(1, "bus_id", pJson["bus_id"], err, false))
            return false;
    }
    if(pJson.isMember("route_id"))
    {
        if(!validJsonOfField(2, "route_id", pJson["route_id"], err, false))
            return false;
    }
    if(pJson.isMember("driver_id"))
    {
        if(!validJsonOfField(3, "driver_id", pJson["driver_id"], err, false))
            return false;
    }
    if(pJson.isMember("conductor_id"))
    {
        if(!validJsonOfField(4, "conductor_id", pJson["conductor_id"], err, false))
            return false;
    }
    if(pJson.isMember("status"))
    {
        if(!validJsonOfField(5, "status", pJson["status"], err, false))
            return false;
    }
    if(pJson.isMember("assignment_date"))
    {
        if(!validJsonOfField(6, "assignment_date", pJson["assignment_date"], err, false))
            return false;
    }
    if(pJson.isMember("created_at"))
    {
        if(!validJsonOfField(7, "created_at", pJson["created_at"], err, false))
            return false;
    }
    return true;
}
bool BusAssignments::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                      const std::vector<std::string> &pMasqueradingVector,
                                                      std::string &err)
{
    if(pMasqueradingVector.size() != 8)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
      if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
      {
          if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool BusAssignments::validJsonOfField(size_t index,
                                      const std::string &fieldName,
                                      const Json::Value &pJson,
                                      std::string &err,
                                      bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 50)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 50)";
                return false;
            }
            break;
        case 6:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 7:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
