/**
 *
 *  BusLocations.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "BusLocations.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::postgres;

const std::string BusLocations::Cols::_id = "\"id\"";
const std::string BusLocations::Cols::_bus_id = "\"bus_id\"";
const std::string BusLocations::Cols::_latitude = "\"latitude\"";
const std::string BusLocations::Cols::_longitude = "\"longitude\"";
const std::string BusLocations::Cols::_speed = "\"speed\"";
const std::string BusLocations::Cols::_timestamp = "\"timestamp\"";
const std::string BusLocations::primaryKeyName = "id";
const bool BusLocations::hasPrimaryKey = true;
const std::string BusLocations::tableName = "\"bus_locations\"";

const std::vector<typename BusLocations::MetaData> BusLocations::metaData_={
{"id","std::string","uuid",0,0,1,1},
{"bus_id","std::string","uuid",0,0,0,0},
{"latitude","std::string","numeric",0,0,0,1},
{"longitude","std::string","numeric",0,0,0,1},
{"speed","std::string","numeric",0,0,0,0},
{"timestamp","::trantor::Date","timestamp without time zone",0,0,0,0}
};
const std::string &BusLocations::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
BusLocations::BusLocations(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<std::string>(r["id"].as<std::string>());
        }
        if(!r["bus_id"].isNull())
        {
            busId_=std::make_shared<std::string>(r["bus_id"].as<std::string>());
        }
        if(!r["latitude"].isNull())
        {
            latitude_=std::make_shared<std::string>(r["latitude"].as<std::string>());
        }
        if(!r["longitude"].isNull())
        {
            longitude_=std::make_shared<std::string>(r["longitude"].as<std::string>());
        }
        if(!r["speed"].isNull())
        {
            speed_=std::make_shared<std::string>(r["speed"].as<std::string>());
        }
        if(!r["timestamp"].isNull())
        {
            auto timeStr = r["timestamp"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                timestamp_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 6 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            busId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            latitude_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            longitude_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            speed_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                timestamp_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }

}

BusLocations::BusLocations(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 6)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            busId_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            latitude_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            longitude_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            speed_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[5]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                timestamp_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

BusLocations::BusLocations(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<std::string>(pJson["id"].asString());
        }
    }
    if(pJson.isMember("bus_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["bus_id"].isNull())
        {
            busId_=std::make_shared<std::string>(pJson["bus_id"].asString());
        }
    }
    if(pJson.isMember("latitude"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["latitude"].isNull())
        {
            latitude_=std::make_shared<std::string>(pJson["latitude"].asString());
        }
    }
    if(pJson.isMember("longitude"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["longitude"].isNull())
        {
            longitude_=std::make_shared<std::string>(pJson["longitude"].asString());
        }
    }
    if(pJson.isMember("speed"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["speed"].isNull())
        {
            speed_=std::make_shared<std::string>(pJson["speed"].asString());
        }
    }
    if(pJson.isMember("timestamp"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["timestamp"].isNull())
        {
            auto timeStr = pJson["timestamp"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                timestamp_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void BusLocations::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 6)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            busId_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            latitude_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            longitude_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            speed_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[5]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                timestamp_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void BusLocations::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<std::string>(pJson["id"].asString());
        }
    }
    if(pJson.isMember("bus_id"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["bus_id"].isNull())
        {
            busId_=std::make_shared<std::string>(pJson["bus_id"].asString());
        }
    }
    if(pJson.isMember("latitude"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["latitude"].isNull())
        {
            latitude_=std::make_shared<std::string>(pJson["latitude"].asString());
        }
    }
    if(pJson.isMember("longitude"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["longitude"].isNull())
        {
            longitude_=std::make_shared<std::string>(pJson["longitude"].asString());
        }
    }
    if(pJson.isMember("speed"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["speed"].isNull())
        {
            speed_=std::make_shared<std::string>(pJson["speed"].asString());
        }
    }
    if(pJson.isMember("timestamp"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["timestamp"].isNull())
        {
            auto timeStr = pJson["timestamp"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                timestamp_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

const std::string &BusLocations::getValueOfId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<std::string> &BusLocations::getId() const noexcept
{
    return id_;
}
void BusLocations::setId(const std::string &pId) noexcept
{
    id_ = std::make_shared<std::string>(pId);
    dirtyFlag_[0] = true;
}
void BusLocations::setId(std::string &&pId) noexcept
{
    id_ = std::make_shared<std::string>(std::move(pId));
    dirtyFlag_[0] = true;
}
const typename BusLocations::PrimaryKeyType & BusLocations::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const std::string &BusLocations::getValueOfBusId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(busId_)
        return *busId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &BusLocations::getBusId() const noexcept
{
    return busId_;
}
void BusLocations::setBusId(const std::string &pBusId) noexcept
{
    busId_ = std::make_shared<std::string>(pBusId);
    dirtyFlag_[1] = true;
}
void BusLocations::setBusId(std::string &&pBusId) noexcept
{
    busId_ = std::make_shared<std::string>(std::move(pBusId));
    dirtyFlag_[1] = true;
}
void BusLocations::setBusIdToNull() noexcept
{
    busId_.reset();
    dirtyFlag_[1] = true;
}

const std::string &BusLocations::getValueOfLatitude() const noexcept
{
    static const std::string defaultValue = std::string();
    if(latitude_)
        return *latitude_;
    return defaultValue;
}
const std::shared_ptr<std::string> &BusLocations::getLatitude() const noexcept
{
    return latitude_;
}
void BusLocations::setLatitude(const std::string &pLatitude) noexcept
{
    latitude_ = std::make_shared<std::string>(pLatitude);
    dirtyFlag_[2] = true;
}
void BusLocations::setLatitude(std::string &&pLatitude) noexcept
{
    latitude_ = std::make_shared<std::string>(std::move(pLatitude));
    dirtyFlag_[2] = true;
}

const std::string &BusLocations::getValueOfLongitude() const noexcept
{
    static const std::string defaultValue = std::string();
    if(longitude_)
        return *longitude_;
    return defaultValue;
}
const std::shared_ptr<std::string> &BusLocations::getLongitude() const noexcept
{
    return longitude_;
}
void BusLocations::setLongitude(const std::string &pLongitude) noexcept
{
    longitude_ = std::make_shared<std::string>(pLongitude);
    dirtyFlag_[3] = true;
}
void BusLocations::setLongitude(std::string &&pLongitude) noexcept
{
    longitude_ = std::make_shared<std::string>(std::move(pLongitude));
    dirtyFlag_[3] = true;
}

const std::string &BusLocations::getValueOfSpeed() const noexcept
{
    static const std::string defaultValue = std::string();
    if(speed_)
        return *speed_;
    return defaultValue;
}
const std::shared_ptr<std::string> &BusLocations::getSpeed() const noexcept
{
    return speed_;
}
void BusLocations::setSpeed(const std::string &pSpeed) noexcept
{
    speed_ = std::make_shared<std::string>(pSpeed);
    dirtyFlag_[4] = true;
}
void BusLocations::setSpeed(std::string &&pSpeed) noexcept
{
    speed_ = std::make_shared<std::string>(std::move(pSpeed));
    dirtyFlag_[4] = true;
}
void BusLocations::setSpeedToNull() noexcept
{
    speed_.reset();
    dirtyFlag_[4] = true;
}

const ::trantor::Date &BusLocations::getValueOfTimestamp() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(timestamp_)
        return *timestamp_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &BusLocations::getTimestamp() const noexcept
{
    return timestamp_;
}
void BusLocations::setTimestamp(const ::trantor::Date &pTimestamp) noexcept
{
    timestamp_ = std::make_shared<::trantor::Date>(pTimestamp);
    dirtyFlag_[5] = true;
}
void BusLocations::setTimestampToNull() noexcept
{
    timestamp_.reset();
    dirtyFlag_[5] = true;
}

void BusLocations::updateId(const uint64_t id)
{
}

const std::vector<std::string> &BusLocations::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "id",
        "bus_id",
        "latitude",
        "longitude",
        "speed",
        "timestamp"
    };
    return inCols;
}

void BusLocations::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getId())
        {
            binder << getValueOfId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getBusId())
        {
            binder << getValueOfBusId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getLatitude())
        {
            binder << getValueOfLatitude();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getLongitude())
        {
            binder << getValueOfLongitude();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getSpeed())
        {
            binder << getValueOfSpeed();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getTimestamp())
        {
            binder << getValueOfTimestamp();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> BusLocations::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    return ret;
}

void BusLocations::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getId())
        {
            binder << getValueOfId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getBusId())
        {
            binder << getValueOfBusId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getLatitude())
        {
            binder << getValueOfLatitude();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getLongitude())
        {
            binder << getValueOfLongitude();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getSpeed())
        {
            binder << getValueOfSpeed();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getTimestamp())
        {
            binder << getValueOfTimestamp();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value BusLocations::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getBusId())
    {
        ret["bus_id"]=getValueOfBusId();
    }
    else
    {
        ret["bus_id"]=Json::Value();
    }
    if(getLatitude())
    {
        ret["latitude"]=getValueOfLatitude();
    }
    else
    {
        ret["latitude"]=Json::Value();
    }
    if(getLongitude())
    {
        ret["longitude"]=getValueOfLongitude();
    }
    else
    {
        ret["longitude"]=Json::Value();
    }
    if(getSpeed())
    {
        ret["speed"]=getValueOfSpeed();
    }
    else
    {
        ret["speed"]=Json::Value();
    }
    if(getTimestamp())
    {
        ret["timestamp"]=getTimestamp()->toDbStringLocal();
    }
    else
    {
        ret["timestamp"]=Json::Value();
    }
    return ret;
}

std::string BusLocations::toString() const
{
    return toJson().toStyledString();
}

Json::Value BusLocations::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 6)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getBusId())
            {
                ret[pMasqueradingVector[1]]=getValueOfBusId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getLatitude())
            {
                ret[pMasqueradingVector[2]]=getValueOfLatitude();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getLongitude())
            {
                ret[pMasqueradingVector[3]]=getValueOfLongitude();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getSpeed())
            {
                ret[pMasqueradingVector[4]]=getValueOfSpeed();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getTimestamp())
            {
                ret[pMasqueradingVector[5]]=getTimestamp()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getBusId())
    {
        ret["bus_id"]=getValueOfBusId();
    }
    else
    {
        ret["bus_id"]=Json::Value();
    }
    if(getLatitude())
    {
        ret["latitude"]=getValueOfLatitude();
    }
    else
    {
        ret["latitude"]=Json::Value();
    }
    if(getLongitude())
    {
        ret["longitude"]=getValueOfLongitude();
    }
    else
    {
        ret["longitude"]=Json::Value();
    }
    if(getSpeed())
    {
        ret["speed"]=getValueOfSpeed();
    }
    else
    {
        ret["speed"]=Json::Value();
    }
    if(getTimestamp())
    {
        ret["timestamp"]=getTimestamp()->toDbStringLocal();
    }
    else
    {
        ret["timestamp"]=Json::Value();
    }
    return ret;
}

bool BusLocations::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("bus_id"))
    {
        if(!validJsonOfField(1, "bus_id", pJson["bus_id"], err, true))
            return false;
    }
    if(pJson.isMember("latitude"))
    {
        if(!validJsonOfField(2, "latitude", pJson["latitude"], err, true))
            return false;
    }
    else
    {
        err="The latitude column cannot be null";
        return false;
    }
    if(pJson.isMember("longitude"))
    {
        if(!validJsonOfField(3, "longitude", pJson["longitude"], err, true))
            return false;
    }
    else
    {
        err="The longitude column cannot be null";
        return false;
    }
    if(pJson.isMember("speed"))
    {
        if(!validJsonOfField(4, "speed", pJson["speed"], err, true))
            return false;
    }
    if(pJson.isMember("timestamp"))
    {
        if(!validJsonOfField(5, "timestamp", pJson["timestamp"], err, true))
            return false;
    }
    return true;
}
bool BusLocations::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                      const std::vector<std::string> &pMasqueradingVector,
                                                      std::string &err)
{
    if(pMasqueradingVector.size() != 6)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[3] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool BusLocations::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("bus_id"))
    {
        if(!validJsonOfField(1, "bus_id", pJson["bus_id"], err, false))
            return false;
    }
    if(pJson.isMember("latitude"))
    {
        if(!validJsonOfField(2, "latitude", pJson["latitude"], err, false))
            return false;
    }
    if(pJson.isMember("longitude"))
    {
        if(!validJsonOfField(3, "longitude", pJson["longitude"], err, false))
            return false;
    }
    if(pJson.isMember("speed"))
    {
        if(!validJsonOfField(4, "speed", pJson["speed"], err, false))
            return false;
    }
    if(pJson.isMember("timestamp"))
    {
        if(!validJsonOfField(5, "timestamp", pJson["timestamp"], err, false))
            return false;
    }
    return true;
}
bool BusLocations::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                    const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err)
{
    if(pMasqueradingVector.size() != 6)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool BusLocations::validJsonOfField(size_t index,
                                    const std::string &fieldName,
                                    const Json::Value &pJson,
                                    std::string &err,
                                    bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
